version: '3'
services:
    app:
        build:
          context: ./
        #   target: development
        command: rails s -b 0.0.0.0
        volumes:
            - .:/usr/src
        ports:
            - "3000:3000"
        depends_on:
            - db
            - cost_server
    cost_server:
        build: 
          context: ../05_homework_ruby-server_v2.0
        ports:
        - "3001:3001"
    db:
        image: postgres:11.5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
